---
title: "Basic Documentation"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
params:
  nameFile: !r 1
  fileType: !r 2017
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
## Note the basic structure/organisation comes from this excellent
## guide here: https://rviews.rstudio.com/2017/11/07/automating-summary-of-surveys-with-rmarkdown/


require(knitr)
require(tidyverse)
require(skimr)

```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
location <- paste("../", params$nameFile, sep = "")

data <- tryCatch(utils::read.csv(location, 
                        stringsAsFactors = FALSE, sep = ","), 
                 error = function(e) NULL)

# solution discussed here: https://stackoverflow.com/questions/13613270/how-to-fix-the-error-in-r-of-no-lines-available-in-input?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
```

# `r params$nameFile` documentation

The basic structure of the file is as follows:

    * There are `r nrow(data)` rows
    * There are `r ncol(data)` columns
    
The column names are given as: `r colnames(data)`.

A brief overview of the data is provided using the `skimr` package below

```{r, echo = FALSE, message = FALSE, warning = FALSE}
skim(data)
```

